import { useEffect, useMemo, useRef, useState } from "react";
import {
  Play,
  Pause,
  RotateCcw,
  ChevronLeft,
  ChevronRight,
  Camera,
  ScanLine,
  CalendarClock,
  Leaf,
  AlertTriangle,
  Clock,
  Sparkles,
} from "lucide-react";
import clsx from "clsx";
import { InventoryItemCard } from "../components/InventoryItemCard";
import { ReviewItemCard } from "../components/review/ReviewItemCard";
import { DemoItemDetail } from "../components/DemoItemDetail";
import { expiryBadgeContent } from "../lib/format";
import type { DonationItem } from "../lib/types";

interface Manifest {
  fixtures: string[];
}

const noop = () => {};

type StepId = "opening-pitch" | "pipeline" | "inventory" | "inventory-detail" | "review" | "expiry" | "handoff";

interface StepDef {
  id: StepId;
  title: string;
  narrationCue: string;
  durationMs: number;
}

// Generated by scripts/generate_demo_narration.py — one clip per step,
// matching each step's narrationCue verbatim. Re-run that script (it
// overwrites cleanly) if the narrationCue text below ever changes.
const STEP_AUDIO: Record<StepId, string> = {
  "opening-pitch": "/demo/audio/opening-pitch.wav",
  pipeline: "/demo/audio/pipeline-intro.wav",
  inventory: "/demo/audio/pipeline-inventory.wav",
  "inventory-detail": "/demo/audio/inventory-detail.wav",
  review: "/demo/audio/pipeline-review.wav",
  expiry: "/demo/audio/pipeline-expiry.wav",
  handoff: "/demo/audio/handoff.wav",
};

const PIPELINE_PHASES = [
  { icon: Camera, label: "Photo or video in" },
  { icon: ScanLine, label: "Reading the label" },
  { icon: CalendarClock, label: "Cross-checking the expiry date" },
  { icon: Leaf, label: "Checking dietary & nutrition symbols" },
];

/** Self-contained: cycles its own phase index on a timer sized to fit
 * durationMs, independent of the outer step timer. Holds on the last phase
 * once reached rather than looping, so it doesn't visibly reset right
 * before the outer sequence advances away from it. Only runs while
 * `active` (i.e. Play is pressed) — this used to start unconditionally on
 * mount, which visually looked like the sequence auto-advancing before
 * Play was ever clicked (four phases cycling on their own, silently). */
function PipelineStageVisual({ durationMs, active }: { durationMs: number; active: boolean }) {
  const [phaseIndex, setPhaseIndex] = useState(0);

  useEffect(() => {
    if (!active) {
      setPhaseIndex(0);
      return;
    }
    const perPhase = durationMs / PIPELINE_PHASES.length;
    const id = window.setInterval(() => {
      setPhaseIndex((i) => Math.min(i + 1, PIPELINE_PHASES.length - 1));
    }, perPhase);
    return () => window.clearInterval(id);
  }, [durationMs, active]);

  return (
    <div className="mx-auto max-w-md space-y-3">
      {PIPELINE_PHASES.map((phase, i) => {
        const Icon = phase.icon;
        const state = i < phaseIndex ? "done" : i === phaseIndex ? "active" : "pending";
        return (
          <div
            key={phase.label}
            className={clsx(
              "flex items-center gap-3 rounded-2xl border px-4 py-3 shadow-soft transition-all duration-300",
              state === "active" && "border-terracotta-400/60 bg-terracotta-100/60 scale-[1.02]",
              state === "done" && "border-success-400/40 bg-success-100/50",
              state === "pending" && "border-cream-300 bg-cream-50 opacity-50"
            )}
          >
            <Icon
              size={18}
              className={clsx(
                state === "active" && "text-terracotta-600",
                state === "done" && "text-success-600",
                state === "pending" && "text-ink-700/40"
              )}
            />
            <span className="text-sm font-medium text-ink-800">{phase.label}</span>
          </div>
        );
      })}
    </div>
  );
}

function StepCaption({ children }: { children: string }) {
  return <p className="mx-auto max-w-lg text-center text-sm text-ink-700/70">{children}</p>;
}

/**
 * One-click narrated walkthrough for recording the demo video's opening
 * pitch + pipeline-explainer segments — for recording without depending
 * on live Bedrock/Gemini extraction. Lands on a static cover page (no
 * autoplay); clicking "Play Demo" starts a single continuous sequence —
 * opening-pitch -> pipeline -> inventory -> inventory-detail -> review ->
 * (optional expiry) -> handoff — all driven by the same audio-`ended`
 * advance mechanism, no second click required partway through.
 *
 * Reads whatever fixture names are listed in /demo/manifest.json
 * (public/demo/), so dropping in a new fixture (e.g. via
 * scripts/capture_demo_fixture.py) never requires a code change here.
 * Zero calls to the real API at any step: fixture JSON, images, and
 * narration audio are all served as static files from this app's own
 * origin, and image_urls/thumbnail_urls are rewritten to that same origin
 * so resolveImageUrl's absolute-URL passthrough kicks in instead of
 * pointing them at the backend. Header/nav come from the shared NavBar in
 * App.tsx, present for every step of the sequence, not just on initial
 * load.
 */
export function DemoPage() {
  const [items, setItems] = useState<DonationItem[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [stepIndex, setStepIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);
  // Cover page ("Play Demo" button, nothing auto-playing) vs. the running
  // sequence. One-way flip — once true, Prev/Next/dots can still scrub
  // back to the opening-pitch step's content, but the dedicated cover
  // screen itself never reappears (Replay just restarts the sequence
  // from step 0, not this flag).
  const [hasStarted, setHasStarted] = useState(false);

  useEffect(() => {
    let cancelled = false;

    async function load() {
      try {
        const manifestRes = await fetch("/demo/manifest.json");
        if (!manifestRes.ok) throw new Error(`manifest.json: ${manifestRes.status}`);
        const manifest: Manifest = await manifestRes.json();

        const loaded = await Promise.all(
          manifest.fixtures.map(async (name) => {
            const res = await fetch(`/demo/${name}.json`);
            if (!res.ok) throw new Error(`${name}.json: ${res.status}`);
            const item: DonationItem = await res.json();
            // Absolute-ify so resolveImageUrl's ^https?:// check treats
            // these as already-final URLs instead of rewriting them onto
            // the API origin. Everything else is left exactly as authored
            // in the fixture — no aggregation, no recomputation — so
            // quantity/expiry_status/etc. always match the JSON verbatim.
            item.image_urls = item.image_urls.map((u) => `${window.location.origin}${u}`);
            item.thumbnail_urls = item.thumbnail_urls.map((u) => `${window.location.origin}${u}`);
            return item;
          })
        );

        if (!cancelled) setItems(loaded);
      } catch (err) {
        if (!cancelled) setError(err instanceof Error ? err.message : "Couldn't load demo fixtures.");
      }
    }

    load();
    return () => {
      cancelled = true;
    };
  }, []);

  const { steps, inventoryItem, reviewItem, expiryItem } = useMemo(() => {
    const committed = items?.filter((i) => !i.requires_human_review) ?? [];
    const flagged = items?.filter((i) => i.requires_human_review) ?? [];

    // Prefer a genuinely "fine" item for the Inventory beat, so it stays
    // honest with the "clean items go straight to inventory" narration —
    // falls back to whatever's first if none happen to be fine right now.
    const inventoryItem = committed.find((i) => i.expiry_status === "fine") ?? committed[0] ?? null;
    const reviewItem = flagged[0] ?? null;
    // A different committed item that's genuinely near/at expiry right
    // now — expiry_status is recomputed fresh server-side on every real
    // read, so which fixture qualifies can change day to day (run
    // scripts/refresh_demo_fixture_expiry.py before recording to keep
    // these fixture values current).
    const expiryItem =
      committed.find(
        (i) => i.item_id !== inventoryItem?.item_id && (i.expiry_status === "near_expiry" || i.expiry_status === "expired")
      ) ?? null;

    const steps: StepDef[] = [
      {
        id: "opening-pitch",
        title: "strand_sort",
        narrationCue:
          "Every day, food banks receive donations they can't move fast enough. Volunteers manually check expiry dates, decode nutrition labels, and guess at dietary categories — one item at a time. It's slow, error-prone, and it takes hours away from the work that actually matters: getting food to the people who need it. strand_sort is an autonomous AI agent, built on AWS Strands, that does this instantly. Point a camera at a donation, and the agent reads the label, verifies the expiry date, checks dietary and nutrition symbols straight off the packaging, and either adds it to inventory or flags it for a human to double-check — without a volunteer typing a single field. This matters because food banks run on volunteer hours, not headcount. Every minute saved sorting donations is a minute spent serving the community they exist for.",
        durationMs: 54000, // real clip: 53.0s
      },
      {
        id: "pipeline",
        title: "How it works",
        narrationCue:
          "A photo or video goes in — strand_sort reads the label, cross-checks the expiry date, and pulls dietary and nutrition details straight from the packaging.",
        // Fallback-only (see the auto-advance effect below) — the real
        // clip is 10.6s; matches scripts/generate_demo_narration.py's
        // measured output, with a little breathing room.
        durationMs: 11000,
      },
      {
        id: "inventory",
        title: "Clean items go straight to inventory",
        narrationCue: "Clean items go straight to inventory.",
        durationMs: 3500, // real clip: 3.2s
      },
    ];
    if (inventoryItem) {
      // The detour into the full item detail view — only makes sense if
      // there's actually an item to show it for.
      steps.push({
        id: "inventory-detail",
        title: "Every item's full record, one tap away",
        narrationCue:
          "Every item's full record is one tap away — the expiry date and how confident the read is, dietary and nutrition flags that show whether they came straight off the package or were inferred, and a distribute panel to track stock as it goes out the door.",
        durationMs: 17000, // real clip: 16.3s
      });
    }
    steps.push({
      id: "review",
      title: "Anything uncertain gets flagged",
      narrationCue:
        "Anything uncertain — a low-confidence date, a damaged label — gets flagged for a quick human check instead of a risky guess.",
      durationMs: 9500, // real clip: 9.2s
    });
    if (expiryItem) {
      steps.push({
        id: "expiry",
        title: "Expiry status, recalculated fresh",
        narrationCue: "Expiry status is never stale — it's recalculated fresh every time an item is viewed.",
        durationMs: 7000, // real clip: 6.6s
      });
    }
    steps.push({
      id: "handoff",
      title: "Now over to an actual demo",
      narrationCue: "Now over to an actual demo.",
      durationMs: 3500, // real clip: 2.8s
    });

    return { steps, inventoryItem, reviewItem, expiryItem };
  }, [items]);

  const audioRef = useRef<HTMLAudioElement>(null);
  const detailRef = useRef<HTMLDivElement>(null);

  // The inventory-detail step's content (image gallery + four sections)
  // is taller than one viewport, and the narration talks through it top
  // to bottom (dates, dietary flags, ... distribute). A one-time
  // scroll-to-top on entry isn't enough — arriving here right after the
  // short "inventory" card step, the page is usually already near the
  // top, so that alone is invisible. Instead, scroll progressively
  // through the content in sync with the narration clip's own playback
  // position (audio.currentTime / audio.duration), so the reveal tracks
  // whatever's actually being said, not a separate guessed timer. Manual
  // Prev/Next/dot navigation while paused just snaps to the top once —
  // no progressive scroll without Play, consistent with every other
  // audio/animation effect in this sequence.
  useEffect(() => {
    if (steps[stepIndex]?.id !== "inventory-detail") return;
    const el = detailRef.current;
    if (!el) return;

    const startY = Math.max(el.getBoundingClientRect().top + window.scrollY - 80, 0);
    window.scrollTo({ top: startY, behavior: "auto" });

    const audio = audioRef.current;
    if (!isPlaying || !audio) return;

    const endY = el.getBoundingClientRect().bottom + window.scrollY - window.innerHeight + 40;
    if (endY <= startY) return; // content already fits in one viewport

    // Driven by requestAnimationFrame, not the audio's own "timeupdate"
    // event — timeupdate fires quite infrequently and irregularly (often
    // just a handful of times per second), so scrolling only on that
    // event produced big, visible jumps rather than continuous motion.
    // Re-reading audio.currentTime every animation frame instead gives
    // ~60fps smooth motion while still tracking the real playback
    // position, not a separate guessed timer.
    let rafId: number;
    const tick = () => {
      if (audio.duration && !Number.isNaN(audio.duration)) {
        const progress = Math.min(audio.currentTime / audio.duration, 1);
        window.scrollTo({ top: startY + (endY - startY) * progress, behavior: "auto" });
        if (progress >= 1) return;
      }
      rafId = requestAnimationFrame(tick);
    };
    rafId = requestAnimationFrame(tick);

    return () => cancelAnimationFrame(rafId);
  }, [stepIndex, steps, isPlaying]);

  // Auto-advance is driven by the current step's narration clip actually
  // finishing (its "ended" event), not a hardcoded duration guess — a
  // fixed-timer approach previously here left the audio silent (nothing
  // ever called .play()) and could drift out of sync with however long
  // the generated clip really runs. Falls back to the fixed-duration
  // timer only if playback itself fails (e.g. autoplay blocked).
  useEffect(() => {
    const audio = audioRef.current;
    if (!isPlaying || steps.length === 0) return;

    const step = steps[stepIndex];
    const advance = () => {
      setStepIndex((i) => {
        if (i >= steps.length - 1) {
          setIsPlaying(false);
          return i;
        }
        return i + 1;
      });
    };

    const audioPath = STEP_AUDIO[step.id];
    if (!audio || !audioPath) {
      const timer = window.setTimeout(advance, step.durationMs);
      return () => window.clearTimeout(timer);
    }

    audio.src = `${window.location.origin}${audioPath}`;
    audio.currentTime = 0;
    audio.addEventListener("ended", advance);
    let fallbackTimer: number | undefined;
    audio.play().catch(() => {
      // Blocked or failed — still advance the visual sequence on the
      // estimated duration rather than stalling silently forever.
      fallbackTimer = window.setTimeout(advance, step.durationMs);
    });

    return () => {
      audio.removeEventListener("ended", advance);
      if (fallbackTimer) window.clearTimeout(fallbackTimer);
    };
  }, [isPlaying, stepIndex, steps]);

  if (error) {
    return <p className="text-sm text-danger-600">Demo fixtures failed to load: {error}</p>;
  }

  if (!items || steps.length === 0) {
    return <p className="text-sm text-ink-700/60">Loading demo fixtures…</p>;
  }

  const currentStep = steps[stepIndex];
  const atEnd = stepIndex === steps.length - 1;

  const togglePlay = () => {
    if (!isPlaying) {
      if (atEnd) setStepIndex(0);
      setIsPlaying(true);
    } else {
      setIsPlaying(false);
      audioRef.current?.pause();
    }
  };

  const goTo = (i: number) => {
    setStepIndex(Math.max(0, Math.min(steps.length - 1, i)));
  };

  const handleStartDemo = () => {
    setStepIndex(0);
    setIsPlaying(true);
    setHasStarted(true);
  };

  if (!hasStarted) {
    return (
      <div className="flex min-h-[60vh] flex-col items-center justify-center gap-8 text-center">
        <div className="flex flex-col items-center gap-3 animate-fade-up">
          <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-terracotta-500 text-3xl shadow-soft">
            🧺
          </div>
          <div>
            <h1 className="font-display text-3xl font-semibold text-ink-900 sm:text-4xl">Strand Sort</h1>
            <p className="mt-1 text-ink-700/70">Donation intake &amp; sorting</p>
          </div>
        </div>
        <button
          onClick={handleStartDemo}
          className="inline-flex items-center gap-2 rounded-full bg-terracotta-500 px-6 py-3 text-base font-semibold text-cream-50 shadow-soft transition-colors hover:bg-terracotta-600"
        >
          <Play size={18} />
          Play Demo
        </button>
      </div>
    );
  }

  return (
    <div className="space-y-8">
      {/* Not rendered visually — playback is driven entirely by the
          auto-advance effect above via audioRef. */}
      <audio ref={audioRef} className="hidden" />

      <div className="animate-fade-up flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-terracotta-400/40 bg-terracotta-100/50 px-4 py-3 text-sm text-terracotta-700">
        <span>Demo mode — static fixtures, no live scans or API calls.</span>
        <div className="flex items-center gap-1">
          {steps.map((step, i) => (
            <button
              key={step.id}
              onClick={() => goTo(i)}
              aria-label={`Go to ${step.title}`}
              className={clsx(
                "h-2 rounded-full transition-all",
                i === stepIndex ? "w-6 bg-terracotta-500" : "w-2 bg-terracotta-300/60 hover:bg-terracotta-400"
              )}
            />
          ))}
        </div>
      </div>

      <div key={currentStep.id} className="animate-fade-up space-y-4">
        {/* opening-pitch and handoff have their own self-contained hero
            treatments below — a generic step title above them would just
            repeat the same text a second time. */}
        {currentStep.id !== "opening-pitch" && currentStep.id !== "handoff" && (
          <div className="text-center">
            <h2 className="font-display text-xl font-semibold text-ink-900 sm:text-2xl">{currentStep.title}</h2>
          </div>
        )}

        {currentStep.id === "opening-pitch" && (
          <div className="space-y-6">
            <div className="flex flex-col items-center gap-3">
              <div className="flex h-16 w-16 items-center justify-center rounded-2xl bg-terracotta-500 text-3xl shadow-soft">
                🧺
              </div>
              <div className="text-center">
                <h1 className="font-display text-3xl font-semibold text-ink-900 sm:text-4xl">Strand Sort</h1>
                <p className="mt-1 text-ink-700/70">Donation intake &amp; sorting</p>
              </div>
            </div>
            <StepCaption>{currentStep.narrationCue}</StepCaption>
          </div>
        )}

        {currentStep.id === "pipeline" && (
          <div className="space-y-4">
            <PipelineStageVisual durationMs={currentStep.durationMs} active={isPlaying} />
            <StepCaption>{currentStep.narrationCue}</StepCaption>
          </div>
        )}

        {currentStep.id === "inventory" && (
          <div className="space-y-4">
            {inventoryItem ? (
              <div className="mx-auto max-w-md">
                <InventoryItemCard
                  item={inventoryItem}
                  onImageRetry={noop}
                  linkTo={`/demo/item/${inventoryItem.item_id}`}
                  readOnly
                />
              </div>
            ) : (
              <StepCaption>No committed fixture available.</StepCaption>
            )}
            <StepCaption>{currentStep.narrationCue}</StepCaption>
          </div>
        )}

        {currentStep.id === "inventory-detail" && inventoryItem && (
          <div ref={detailRef} className="space-y-4">
            <DemoItemDetail item={inventoryItem} />
            <StepCaption>{currentStep.narrationCue}</StepCaption>
          </div>
        )}

        {currentStep.id === "review" && (
          <div className="space-y-4">
            {reviewItem ? (
              <div className="mx-auto max-w-md">
                <ReviewItemCard
                  item={reviewItem}
                  isResolving={false}
                  isLeaving={false}
                  onApprove={noop}
                  onReject={noop}
                  onImageRetry={noop}
                />
              </div>
            ) : (
              <div className="mx-auto flex max-w-md items-start gap-2 rounded-2xl border border-dashed border-cream-300 bg-cream-50 px-4 py-3.5 text-sm text-ink-700/70">
                <AlertTriangle size={16} className="mt-0.5 shrink-0 text-ink-700/40" />
                <p>
                  No flagged example captured yet. Run{" "}
                  <code className="rounded bg-cream-200 px-1 py-0.5 text-xs">
                    scripts/capture_demo_fixture.py
                  </code>{" "}
                  against a real flagged photo to add one — it'll show up here automatically.
                </p>
              </div>
            )}
            <StepCaption>{currentStep.narrationCue}</StepCaption>
          </div>
        )}

        {currentStep.id === "expiry" && expiryItem && (
          <div className="space-y-4">
            <div className="mx-auto max-w-md space-y-2">
              <InventoryItemCard
                item={expiryItem}
                onImageRetry={noop}
                linkTo={`/demo/item/${expiryItem.item_id}`}
                readOnly
              />
              <div className="flex items-center justify-center gap-1.5 text-xs text-ink-700/60">
                <Clock size={13} />
                <span>{expiryBadgeContent(expiryItem.expiry_status, expiryItem.expiration_date).label}</span>
              </div>
            </div>
            <StepCaption>{currentStep.narrationCue}</StepCaption>
          </div>
        )}

        {currentStep.id === "handoff" && (
          <div className="flex flex-col items-center gap-3 py-4 text-center">
            <Sparkles size={28} className="text-terracotta-500" />
            <p className="font-display text-2xl font-semibold text-ink-900">{currentStep.narrationCue}</p>
          </div>
        )}
      </div>

      <div className="flex items-center justify-center gap-3">
        <button
          onClick={() => goTo(stepIndex - 1)}
          disabled={stepIndex === 0}
          aria-label="Previous step"
          className="rounded-full border border-cream-300 bg-cream-50 p-2.5 text-ink-700 shadow-soft transition-colors hover:border-terracotta-300 disabled:opacity-40"
        >
          <ChevronLeft size={16} />
        </button>

        <button
          onClick={togglePlay}
          className="inline-flex items-center gap-2 rounded-full bg-terracotta-500 px-5 py-2.5 text-sm font-semibold text-cream-50 shadow-soft transition-colors hover:bg-terracotta-600"
        >
          {isPlaying ? (
            <>
              <Pause size={15} />
              Pause
            </>
          ) : atEnd ? (
            <>
              <RotateCcw size={15} />
              Replay
            </>
          ) : (
            <>
              <Play size={15} />
              Play
            </>
          )}
        </button>

        <button
          onClick={() => goTo(stepIndex + 1)}
          disabled={atEnd}
          aria-label="Next step"
          className="rounded-full border border-cream-300 bg-cream-50 p-2.5 text-ink-700 shadow-soft transition-colors hover:border-terracotta-300 disabled:opacity-40"
        >
          <ChevronRight size={16} />
        </button>
      </div>
    </div>
  );
}
